name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run PyLint
      uses: ricardochaves/python-lint@v1.3.0
      with:
        python-root-list: "."
        use-pylint: true
        use-pycodestyle: false
        use-flake8: false
        use-black: false
        use-mypy: false
        use-isort: false
        extra-pylint-options: "--rcfile=.pylintrc"
        extra-pycodestyle-options: ""
        extra-flake8-options: ""
        extra-black-options: ""
        extra-mypy-options: ""
        extra-isort-options: ""
    - name: Build docker image
      run: make docker-build
    - name: Run tests
      run: make docker-runtest-all
